from __future__ import annotations

DEPOSIT_STATUS_PENDING = "pending"
DEPOSIT_STATUS_APPROVED = "approved"
DEPOSIT_STATUS_REJECTED = "rejected"

CRYPTO_STATUS_PENDING_PAYMENT = "pending_payment"
CRYPTO_STATUS_DETECTED = "detected"
CRYPTO_STATUS_APPROVED = "approved"
CRYPTO_STATUS_REJECTED = "rejected"

ORDER_STATUS_WAITING_INFO = "waiting_user_info"
ORDER_STATUS_PENDING_ADMIN = "pending_admin"
ORDER_STATUS_COMPLETED = "completed"
ORDER_STATUS_CANCELLED = "cancelled"

WITHDRAWAL_STATUS_PENDING = "pending"
WITHDRAWAL_STATUS_PAID_WAITING_PROOF = "paid_waiting_proof"
WITHDRAWAL_STATUS_COMPLETED = "completed"
WITHDRAWAL_STATUS_REJECTED = "rejected"

LOG_ENTITY_BANK_DEPOSIT = "bank_deposit"
LOG_ENTITY_CRYPTO_DEPOSIT = "crypto_deposit"
LOG_ENTITY_ORDER = "order"
LOG_ENTITY_USER = "user"
LOG_ENTITY_GAME = "game"
LOG_ENTITY_PRODUCT = "product"
LOG_ENTITY_COIN_PACKAGE = "coin_package"
LOG_ENTITY_TEMPLATE = "message_template"
LOG_ENTITY_WITHDRAWAL = "withdrawal"
